ansible_python_interpreter: /usr/bin/python3

sudo_users:
  - { username: ops01, group: ops }

regular_users:
  - { username: dev01, group: dev }
  - { username: dev02, group: dev }
  - { username: mkt01, group: marketing }
  
nfs_mount_path: /mnt/shared
nfs_host_path: /var/nfs_shared

