---
- name: Create folder to store maintenance scripts
  ansible.builtin.file:
    path: "{{script_location}}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Copy scripts to servers
  ansible.builtin.copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    mode: 0755
  with_items: 
    - { src: "health_check.sh", dest: "{{script_location}}/health_check.sh"}
    - { src: "upgrade_server.sh", dest: "{{script_location}}/upgrade_server.sh"}

- name: Ensure health script runs every day at 3AM
  ansible.builtin.cron:
    name: "health check"
    minute: "0"
    hour: "3"
    job: "{{script_location}}/health_check.sh"
  
- name: Create a job which cleans cache every sunday at 4AM
  ansible.builtin.cron:
    name: "cache cleanup"
    minute: "0"
    hour: "4"
    weekday: "7"
    job: "sudo dnf clean all"

- name: Create a job which frequently updates packages
  ansible.builtin.cron:
    name: "update packages"
    minute: "0"
    hour: "0"
    job: "{{script_location}}/upgrade_server.sh"
