backup_group: db_backup
backup_user: db_backup

dest_backup: /var/backups/nexcore

dbs_for_backup:
  - username: mediawiki
    database: mw_db
    pass: mw_password
  - username: wordpress
    database: wp_db
    pass: wp_password