collections:
  - name: ansible.mysql
    source: https://galaxy.ansible.com
  - name: community.mysql
    source: https://galaxy.ansible.com
  - name: ansible.posix
  - name: community.general
    version: v7.5.0