---
- name: Install dnsmasq DNS service
  ansible.builtin.yum:
    name: dnsmasq
    state: present
  when: inventory_hostname in groups['web_dns']
  
- name: Deploy config for DNS service
  ansible.builtin.template:
    src: templates/dnsmasq_config.j2
    dest: /etc/dnsmasq.d/00-ansible-dns.conf
  when: inventory_hostname in groups['web_dns']

- name: Check configuration syntax
  ansible.builtin.command: dnsmasq --test
  register: dnsmasq_syntax_check
  ignore_errors: true
  when: inventory_hostname in groups['web_dns']
  
- name: Print syntax check status
  ansible.builtin.debug:
    msg: "{{dnsmasq_syntax_check}}"
  when: inventory_hostname in groups['web_dns']

- name: Comment out "bind-interfaces" line from /etc/dnsmasq.conf
  ansible.builtin.replace:
    dest: /etc/dnsmasq.conf
    regexp: '^bind-interfaces'
    replace: '#bind-interfaces'
  when: inventory_hostname in groups['web_dns'] 

- name: Enable and restart dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true
  when: inventory_hostname in groups['web_dns'] and 'syntax check OK' in dnsmasq_syntax_check.stderr

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: yes
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - reload NetworkManager

- name: Remove immutable attribute from resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    attributes: -i
  ignore_errors: true

- name: Create backup of current /etc/resolv.conf
  ansible.builtin.command: mv /etc/resolv.conf /etc/resolv.conf.bak
  ignore_errors: true

- name: Set /etc/resolv.conf to resolve a custom DNS
  ansible.builtin.template:
    src: templates/resolv_conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - reload NetworkManager

- name: Add back immutable attribute from resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    attributes: +i

  