db_packages:
  - mariadb-server 
  - php
  - php-mysqlnd
  - php-gd
  - php-xml
  - php-mbstring
  - php-json
  - php-intl
  - python3-PyMySQL
mysql_root_password: "db_password_#321"

wordpress_packages:
  - php
  - php-mysqlnd
  - php-gd
  - php-xml
  - php-mbstring
  - php-json
  - php-intl

mediawiki_packages:
  - php
  - php-mysqlnd
  - php-gd
  - php-xml
  - php-mbstring
  - php-json
  - php-intl

mediawiki_document_root: /var/www/html
mediawiki_error_log: /var/log/httpd/mediawiki_error.log
mediawiki_custom_log: /var/log/httpd/mediawiki_access.log
mediawiki_custom_log_type: combined
mediawiki_download_url: "https://releases.wikimedia.org/mediawiki/1.37/mediawiki-1.37.1.tar.gz"
mediawiki_httpd_port: 80
mediawiki_server_name: wiki.nexcore.local

wordpress_download_url: "https://wordpress.org/latest.tar.gz"
wordpress_document_root: /var/www/html
wordpress_error_log: /var/log/httpd/wordpress_error.log
wordpress_custom_log: /var/log/httpd/wordpress_access.log
wordpress_custom_log_type: combined
wordpress_httpd_port: 80
wordpress_server_name: www.nexcore.local