---
- name: Allow needed ports through firewall (web)
  ansible.posix.firewalld:
    port: "{{item}}/tcp"
    permanent: true
    state: enabled
  with_items: "{{ firewall_allowed_ports_db }}"

- name: Allow needed protocols through firewall (db)
  ansible.posix.firewalld:
    protocol: "{{item}}"
    permanent: true
    state: enabled
  with_items: "{{ firewall_allowed_protocols_db }}"

- name: Allow needed services through firewall (db)
  ansible.posix.firewalld:
    service: "{{item}}"
    state: enabled
    permanent: true
    immediate: true
    offline: true
  with_items: "{{ firewall_allowed_services_db }}"
