---
- name: Ensure SELinux is enforcing
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: Ensure firewall is running
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Setup web security
  import_tasks: web_security.yml
  when: inventory_hostname in groups['web_dns']

- name: Setup db security
  import_tasks: db_security.yml
  when: inventory_hostname in groups['db_nfs']






