dns_listen_addresses: "172.25.250.10"
dns_interface: eth0
dns_nameservers:
  - 172.25.250.220

root_dns_domain: nexcore.local
sub_dns_domains:
  - "{{root_dns_domain}}"
  - "www.{{root_dns_domain}}"
  - "wiki.{{root_dns_domain}}"

resolv_main_nameserver: 172.25.250.10