- name: Deploy cron for backing up database nightly
  ansible.builtin.cron:
    name: "nightly database backup - {{ item.database }}"
    weekday: "*"
    minute: "0"
    hour: "1"
    user: "{{ backup_user }}"
    job: "mysqldump --user {{ item.username }} --password {{ item.pass }} {{ item.database }} > {{ dest_backup }}/{{ item.database }}-$(date +%F).sql"
  with_items: "{{ dbs_for_backup }}"