- name: Configure rsyslog to forward all logs to servera over 514/tcp
  ansible.builtin.copy:
    src: files/rsyslog_sender.conf
    dest: /etc/rsyslog.d/50-ansible-sender.conf
  notify: Restart rsyslog