---
- name: Create Company_Share directory for all users
  ansible.builtin.file:
    path: "/home/{{item.username}}/Company_Share"
    state: directory
    mode: 0755
    owner: "{{item.username}}"
    group: "{{item.group}}"
  with_items: "{{ all_users }}"

- name: Create dedicated users subdirectory in NFS share
  ansible.builtin.file:
    path: "{{nfs_host_path}}/users"
    state: directory
    mode: 0777
    owner: root
    group: root
  when: inventory_hostname in groups['db_nfs']

- name: Create subdirectories for every user
  ansible.builtin.file:
    path: "{{nfs_host_path}}/users/{{item.username}}"
    state: directory
    mode: 0755
    owner: "{{item.username}}"
    group: "{{item.group}}"
  with_items: "{{ all_users }}"
  when: inventory_hostname in groups['db_nfs']
            
- name: Configure AutoFS to auto mount directories
  import_tasks: autofs.yml