---
- name: Install dnsmasq DNS service
  ansible.builtin.yum:
    name: dnsmasq
    state: present
  when: inventory_hostname in groups['web_dns']
  
- name: Deploy config for DNS service
  ansible.builtin.template:
    src: templates/dnsmasq_config.j2
    dest: /etc/dnsmasq.d/00-ansible-dns.conf
  when: inventory_hostname in groups['web_dns']

- name: Check configuration syntax
  ansible.builtin.command: dnsmasq --test
  register: dnsmasq_syntax_check
  ignore_errors: true
  when: inventory_hostname in groups['web_dns']
  
- name: Print syntax check status
  ansible.builtin.debug:
    msg: "{{dnsmasq_syntax_check}}"
  when: inventory_hostname in groups['web_dns']

- name: Enable and start dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq
    state: started
    enabled: true
  when: "inventory_hostname in groups['web_dns'] and 'syntax check OK' in dnsmasq_syntax_check"

- name: Set /etc/resolv.conf to resolve a custom DNS
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    regexp: "{{item.reg}}"
    line: "{{item.spec}}"
  with_items: 
    - { reg: '^#?nameserver', spec: "nameserver {{resolv_main_nameserver}}" }
    - { reg: '^#?search', spec: "search lab.example.com example.com {{dns_domain}}"}


  