---
- name: Install database and related packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ db_packages }}"
  when: inventory_hostname in groups['db_nfs']

- name: Start and enable mysql on serverb
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true
  when: inventory_hostname in groups['db_nfs']

- name: Setup MySQL root password
  ansible.mysql.mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  when: inventory_hostname in groups['db_nfs']

- name: Delete anonymous MySQL user
  ansible.mysql.mysql_user: name="" host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ansible_nodename}}"
  when: inventory_hostname in groups['db_nfs']

- name: Remove MySQL test database
  ansible.mysql.mysql_db: name=test state=absent
  when: inventory_hostname in groups['db_nfs']

- name: Check DB connection
  ansible.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: true
  register: mysql_connection_output
  when: inventory_hostname in groups['db_nfs']

- name: Print MySQL status
  ansible.builtin.debug:
    msg: "MySQL state: {{ mysql_connection_output }}"
  when: inventory_hostname in groups['db_nfs']

## konfigurirati mysql (istraziti)

## sloziti python env... community.mysql