---
- name: Download and extract Mediawiki tarball
  ansible.builtin.unarchive:
    src: "{{ mediawiki_download_url }}"
    dest: "{{ mediawiki_document_root }}"
    remote_src: true
    setype: httpd_sys_content_t
  when: inventory_hostname in groups['web_dns']  


# might need to change to SELinux perms
- name: Set apache ownership of mediawiki webpage
  ansible.builtin.file:
    path: "{{ mediawiki_document_root }}"
    owner: apache
    group: apache
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['web_dns']

- name: Deploy configuration for MediaWiki
  ansible.builtin.template:
    src: templates/mediawiki_httpd.j2
    dest: /etc/httpd/conf.d/mediawiki.conf
  when: inventory_hostname in groups['web_dns']

- name: Restart httpd to apply new configuration
  ansible.builtin.systemd_service:
    state: restarted
    name: httpd
    enabled: true
  when: inventory_hostname in groups['web_dns']

- name: Prepare Mediawiki database
  ansible.builtin.command: mysql < mediawiki_db.sql
  register: dbmw_prep_result
  when: inventory_hostname in groups['db_nfs']

- name: Print database result
  ansible.builtin.debug:
    msg: dbmw_prep_result
  when: inventory_hostname in groups['db_nfs']