---
- name: Install related packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ mediawiki_packages }}"
  when: inventory_hostname in groups['web_dns']

# might need to change to SELinux perms
- name: Set apache ownership of mediawiki webpage
  ansible.builtin.file:
    path: "{{ mediawiki_document_root }}"
    owner: apache
    group: apache
    state: directory
    mode: '0755'
    recurse: true
  when: inventory_hostname in groups['web_dns']

- name: Download and extract Mediawiki tarball
  ansible.builtin.unarchive:
    src: "{{ mediawiki_download_url }}"
    dest: "{{ mediawiki_document_root }}"
    remote_src: true
    setype: httpd_sys_content_t
  when: inventory_hostname in groups['web_dns']  

- name: Find extracted mediawiki folder
  ansible.builtin.find:
    paths: "{{ mediawiki_document_root }}"
    file_type: directory
    patterns: "mediawiki-*"
  register: mediawiki_full

# clunky rjesenje, ali za sad je tako
- name: Rename mediawiki directory so httpd can find it
  ansible.builtin.command: "mv {{ mediawiki_full.files[0].path }} mediawiki"
  when: mediawiki_full.matched != 0

# NEED TO ADD EXCEPTION FOR SELINUX
- name: Deploy configuration for MediaWiki
  ansible.builtin.template:
    src: templates/mediawiki_httpd.j2
    dest: /etc/httpd/conf.d/mediawiki.conf
  when: inventory_hostname in groups['web_dns']

- name: Restart httpd to apply new configuration
  ansible.builtin.systemd:
    state: restarted
    name: httpd
    enabled: true
  when: inventory_hostname in groups['web_dns']

- name: Load Mediawiki SQL script
  ansible.builtin.set_fact:
    mw_sql_content: "{{ lookup('file', 'files/mediawiki_db.sql').splitlines()}}"

- name: Prepare Mediawiki database
  ansible.mysql.mysql_query:
    login_host: localhost
    login_user: root
    login_password: "{{mysql_root_password}}"
    query: "{{item}}"
    single_transaction: true
  with_items: "{{mw_sql_content}}"
  register: dbmw_prep_result
  ignore_errors: true
  when: inventory_hostname in groups['db_nfs']

- name: Print database result
  ansible.builtin.debug:
    msg: "{{dbmw_prep_result}}"
  when: inventory_hostname in groups['db_nfs']