---
- name: Install related packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ wordpress_packages }}"
  when: inventory_hostname in groups['web_dns']

# might need to change to SELinux perms
- name: Set apache ownership of Wordpress webpage
  ansible.builtin.file:
    path: "{{ wordpress_document_root }}"
    owner: apache
    group: apache
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['web_dns']

- name: Download and extract Wordpress tarball
  ansible.builtin.unarchive:
    src: "{{ wordpress_download_url }}"
    dest: "{{ wordpress_document_root }}"
    remote_src: true
    setype: httpd_sys_content_t
  when: inventory_hostname in groups['web_dns']

- name: Apply Wordpress database configuration
  ansible.builtin.copy:
    src: files/wordpress_config.php
    dest: "{{ wordpress_document_root }}/wp-config.php"
    owner: apache
    group: apache
    mode: '0755'
  when: inventory_hostname in groups['web_dns']

- name: Deploy configuration for Wordpress
  ansible.builtin.template:
    src: templates/wordpress_httpd.j2
    dest: /etc/httpd/conf.d/wordpress.conf
  when: inventory_hostname in groups['web_dns']

- name: Restart httpd to apply new configuration
  ansible.builtin.systemd:  # novija verzija je systemd_service (ako bude isao upgrade ansiblea)
    state: restarted
    name: httpd
    enabled: true
  when: inventory_hostname in groups['web_dns']

- name: Load Wordpress SQL script
  ansible.builtin.set_fact:
    wp_sql_content: "{{ lookup('file', 'files/wordpress_db.sql').splitlines()}}"

- name: Prepare Wordpress database
  ansible.mysql.mysql_query:
    login_host: localhost
    login_user: root
    login_password: "{{mysql_root_password}}"
    query: "{{item}}"
    single_transaction: true
  with_items: "{{wp_sql_content}}"
  register: dbwp_prep_result
  ignore_errors: true
  when: inventory_hostname in groups['db_nfs']

- name: Print database result
  ansible.builtin.debug:
    msg: dbwp_prep_result
  when: inventory_hostname in groups['db_nfs']
    