postfix_params:
  - { param: inet_interfaces, value: all }
  - { param: myhostname, value: mail.servera.lab.example.com }
  - { param: mydomain, value: nexcore.local }
  - { param: myorigin, value: $mydomain }
  - { param: mydestination, value: "$myhostname, localhost.$mydomain, localhost, $mydomain" }
  - { param: mail_spool_directory, value: /var/mail }
  - { param: mynetworks, value: "127.0.0.0/8, 172.25.250.0/24" }
  - { param: home_mailbox, value: Maildir/ }

home_mailbox: Maildir/

mail_packages:
  - sendmail