postfix_params:
  - { param: myhostname, value: mail.servera.lab.example.com }
  - { param: mydomain, value: nexcore.local }
  - { param: mail_spool_directory, value: /var/mail }
  - { param: mynetworks, value: "172.0.0.0/8, 172.25.250.10/24" }
  - { param: home_mailbox, value: Maildir/ }

home_mailbox: Maildir/