- name: Create receiving folder for logs
  ansible.builtin.file:
    path: "{{rsyslog_receive_path}}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: Configure rsyslog to receive all logs from 514/tcp
  ansible.builtin.template:
    src: templates/rsyslog_receiver.j2
    dest: /etc/rsyslog.d/50-ansible-receiver.conf
  notify: Restart rsyslog