selinux_allowed_httpd_ports:
  - 90 #mediawiki
  - 91 #wordpress
  
firewall_allowed_ports:
  - 90 #mediawiki
  - 91 #wordpress

firewall_allowed_services:
  - httpd
  - nfs-server

firewall_allowed_protocols:
  - nfs