---
- name: Config httpd on servera
  import_tasks: httpd_install.yml
  when: inventory_hostname in groups['web_dns']

- name: Config mysql on serverb
  import_tasks: db_install.yml
  when: inventory_hostname in groups['db_nfs']

- name: Config mediawiki on servera
  import_tasks: mediawiki_setup.yml

- name: Config wordpress on servera
  import_tasks: wordpress_setup.yml


  