---
- name: Install required packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop: "{{ nfs_packages }}"

- name: Start and enable nfs-server
  ansible.builtin.service:
    name: nfs-server
    state: started
    enabled: true
  when: inventory_hostname in groups['db_nfs']

- name: Check if LV device exists
  ansible.builtin.stat:
    path: "/dev/{{vg_name}}/{{lv_name}}"
  register: lvm_stat_result
  when: inventory_hostname in groups['db_nfs']

- name: Create LV for NFS
  import_tasks: nfs_setup.yml
  when: inventory_hostname in groups['db_nfs'] and not lvm_stat_result.stat.exists

- name: Create mount folder on host
  ansible.builtin.file:
    path: "{{ nfs_host_path }}"
    owner: nobody
    group: nobody
    state: directory
    mode: '0777'
  when: inventory_hostname in groups['db_nfs']

- name: Mount LV on host
  ansible.posix.mount:
    path: "{{ nfs_host_path }}"
    src: "/dev/{{vg_name}}/{{lv_name}}"
    fstype: xfs
    state: mounted
  when: inventory_hostname in groups['db_nfs']

- name: Expose LV to NFS
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{nfs_host_path}} *(rw,sync,no_subtree_check,no_root_squash)"
    state: present
  when: inventory_hostname in groups['db_nfs']

- name: Reload NFS export
  ansible.builtin.command: exportfs -ra
  when: inventory_hostname in groups['db_nfs']

# DODATI EXCEPTION U FIREWALL ZA NFS PROTOKOL KASNIJE
- name: Mount shared folder on all servers
  ansible.posix.mount:
    path: "{{ nfs_mount_path }}"
    src: "172.25.250.11:{{nfs_host_path}}"
    opts: rw,sync
    fstype: nfs
    state: mounted
  when: inventory_hostname not in groups['db_nfs']